export interface DataAPIEntity {
    DC_NOME: string;
    PRE_INS: number | string;
    TEM_SEN: string;
    VL_LATITUDE: string;
    PRE_MAX: number | string;
    UF: string;
    RAD_GLO: number | string;
    PTO_INS: number | string;
    TEM_MIN:number | string;
    VL_LONGITUDE: string;
    UMD_MIN:number | string;
    PTO_MAX: number | string;
    VEN_DIR: string;
    DT_MEDICAO: string;
    CHUVA: number | string;
    PRE_MIN:number | string;
    UMD_MAX: number | string;
    VEN_VEL: string;
    PTO_MIN:number | string;
    TEM_MAX: number | string;
    TEN_BAT: string;
    VEN_RAJ: string;
    TEM_CPU: string;
    TEM_INS: number | string;
    UMD_INS: number | string;
    CD_ESTACAO: string;
    HR_MEDICAO?: string;
    TEM_MED?: number | string;
    num_dias?: number | string;
}